services:
  web:
    build: .
    command: python manage.py runserver 0.0.0:8001
    image: readers_web
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - DJANGO_SETTINGS_MODULE=config.settings
      - PYTHONUNBUFFERED=1

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  celery:
    build: .
    command: celery -A config worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - web
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data:
