# Generated by Django 5.2.1 on 2025-07-04 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_carousel_is_advertise'),
    ]

    operations = [
        migrations.AddField(
            model_name='generaldata',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
