# Generated by Django 5.2.1 on 2025-06-18 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_country_generaldata_support_state_city_thana'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='support',
            name='subject',
        ),
    ]
