# Generated by Django 5.2.1 on 2025-06-18 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_support_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='carousel',
            name='subtitle_bn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='carousel',
            name='title_bn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
