# Generated by Django 5.2.1 on 2025-07-05 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_generaldata_delivery_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='name_bn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='name_bn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='name_bn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='thana',
            name='name_bn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='core.state'),
        ),
        migrations.AlterField(
            model_name='thana',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thanas', to='core.city'),
        ),
        migrations.CreateModel(
            name='Union',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('name_bn', models.CharField(max_length=255, null=True)),
                ('thana', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unions', to='core.thana')),
            ],
            options={
                'verbose_name': 'Union',
                'verbose_name_plural': 'Unions',
            },
        ),
    ]
