# Generated by Django 5.2.1 on 2025-06-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash_on_delivery', 'Cash On Delivery'), ('bank_transfer', 'Bank Transfer'), ('bkash', 'Bkash'), ('rocket', 'Rocket'), ('nagad', 'Nagad')], default='cash_on_delivery', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('payment_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_url', models.URLField(blank=True, null=True)),
                ('payment_response', models.JSONField(blank=True, null=True)),
                ('payment_response_code', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_response_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
