# Generated by Django 5.2.1 on 2025-06-22 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='bio_bn',
            field=models.TextField(blank=True, null=True),
        ),
    ]
