# Generated by Django 5.2.1 on 2025-06-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_author_bio_bn'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
