# Generated by Django 5.2.1 on 2025-07-02 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0006_author_email_author_name_author_name_bn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('name_bn', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='author.author')),
            ],
            options={
                'verbose_name': 'Author Tag',
                'verbose_name_plural': 'Author Tags',
            },
        ),
    ]
