# Generated by Django 5.2.1 on 2025-06-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_category_index_number_category_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_bn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
