# Generated by Django 5.2.1 on 2025-06-20 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('name_bn', models.CharField(blank=True, help_text='Bengali name of the special package', max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_bn', models.TextField(blank=True, help_text='Bengali description of the special package', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='special_package_images/')),
                ('index_number', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Featured special package will be shown on the home page')),
            ],
            options={
                'verbose_name': 'Special Package',
            },
        ),
        migrations.CreateModel(
            name='SpecialPackageBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('index_number', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_packages', to='book.book')),
                ('special_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='book.specialpackage')),
            ],
            options={
                'verbose_name': 'Special Package Book',
                'verbose_name_plural': 'Special Package Books',
            },
        ),
    ]
