# Generated by Django 5.2.1 on 2025-06-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_specialpackage_specialpackagebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialpackage',
            name='uuid',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
