# Generated by Django 5.2.1 on 2025-06-18 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_category_name_bn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Featured category will be shown on the home page'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_bn',
            field=models.CharField(blank=True, help_text='Bengali name of the category', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
