# Generated by Django 5.2.1 on 2025-06-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_category_is_featured_alter_category_name_bn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_best_seller',
            field=models.BooleanField(default=False, help_text='If true, the book will be shown on the best seller section'),
        ),
        migrations.AddField(
            model_name='book',
            name='is_comming_soon',
            field=models.BooleanField(default=False, help_text='If true, the book will be shown on the comming soon section'),
        ),
        migrations.AddField(
            model_name='book',
            name='is_favorite',
            field=models.BooleanField(default=False, help_text='If true, the book will be shown on the favorite section'),
        ),
        migrations.AddField(
            model_name='book',
            name='is_new_arrival',
            field=models.BooleanField(default=False, help_text='If true, the book will be shown on the new arrival section'),
        ),
        migrations.AddField(
            model_name='book',
            name='title_bn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='book_images/'),
        ),
    ]
