# Generated by Django 5.2.1 on 2025-06-20 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_specialpackage_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialpackagebook',
            name='special_package',
        ),
        migrations.AddField(
            model_name='specialpackage',
            name='books',
            field=models.ManyToManyField(blank=True, null=True, related_name='special_packages', through='book.SpecialPackageBook', to='book.book'),
        ),
        migrations.AddField(
            model_name='specialpackagebook',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package_books', to='book.specialpackage'),
        ),
        migrations.AlterField(
            model_name='specialpackagebook',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='book.book'),
        ),
    ]
