# Generated by Django 5.2.1 on 2025-06-22 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_remove_specialpackagebook_special_package_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='specialpackage',
            name='books',
            field=models.ManyToManyField(blank=True, related_name='special_packages', through='book.SpecialPackageBook', to='book.book'),
        ),
    ]
