# Generated by Django 5.2.1 on 2025-06-22 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_initial'),
        ('book', '0006_book_is_active_alter_specialpackage_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='author.author'),
        ),
    ]
