# Generated by Django 5.2.1 on 2025-06-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_rename_publisher_book_publisher_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookimage',
            name='index_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookimage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bookimage',
            name='image',
            field=models.ImageField(null=True, upload_to='book_images/'),
        ),
    ]
