# Generated by Django 5.2.1 on 2025-06-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_bookimage_index_number_bookimage_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='is_favorite',
            new_name='is_popular',
        ),
        migrations.AlterField(
            model_name='book',
            name='country',
            field=models.CharField(blank=True, help_text='Country of publication', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='dimensions',
            field=models.CharField(blank=True, help_text="e.g., '5 x 8 inches'", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='in grams', max_digits=5, null=True),
        ),
    ]
