# Generated by Django 5.2.1 on 2025-06-30 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_rename_is_favorite_book_is_popular_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_pdf',
            field=models.FileField(blank=True, null=True, upload_to='book_pdfs/'),
        ),
    ]
