# Generated by Django 5.2.1 on 2025-07-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_book_book_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_pdf',
        ),
        migrations.AddField(
            model_name='book',
            name='book_preview',
            field=models.FileField(blank=True, null=True, upload_to='book_preview/'),
        ),
    ]
