# Generated by Django 5.2.1 on 2025-07-02 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_remove_book_book_pdf_book_book_preview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_preview',
        ),
        migrations.CreateModel(
            name='BookPreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='book_previews/')),
                ('index_number', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previews', to='book.book')),
            ],
            options={
                'verbose_name': 'Book Preview',
                'verbose_name_plural': 'Book Previews',
                'ordering': ['index_number'],
            },
        ),
    ]
