# Generated by Django 5.2.1 on 2025-07-03 16:28

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0014_bookreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='description_bn',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
    ]
