# Generated by Django 5.2.1 on 2025-07-10 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_cart_price_remove_cart_total_price_cart_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
