# Generated by Django 5.2.1 on 2025-07-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cart_is_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_checkout',
            field=models.BooleanField(default=False),
        ),
    ]
