# Generated by Django 5.2.1 on 2025-07-11 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_cart_is_checkout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='is_checkout',
        ),
    ]
