# Generated by Django 5.2.1 on 2025-07-17 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0015_alter_book_description_alter_book_description_bn'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookwishlist',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to='book.book'),
        ),
        migrations.AlterField(
            model_name='bookwishlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
