# Generated by Django 5.2.1 on 2025-06-18 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_category_index_number_category_is_active_and_more'),
        ('user', '0005_alter_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookWishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Book Wish List',
                'verbose_name_plural': 'Book Wish Lists',
            },
        ),
    ]
