# Generated by Django 5.2.1 on 2025-07-05 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_city_name_bn_country_name_bn_state_name_bn_and_more'),
        ('shipping', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipping',
            old_name='address_line_1',
            new_name='detail_address',
        ),
        migrations.RemoveField(
            model_name='shipping',
            name='address_line_2',
        ),
        migrations.RemoveField(
            model_name='shipping',
            name='postal_code',
        ),
        migrations.AddField(
            model_name='shipping',
            name='thana',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping', to='core.thana'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping', to='core.city'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping', to='core.country'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping', to='core.state'),
        ),
    ]
