# Generated by Django 5.2.1 on 2025-07-06 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0003_rename_address_line_1_shipping_detail_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='address_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
