# Generated by Django 5.2.1 on 2025-07-06 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0004_shipping_address_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='address_type',
            field=models.CharField(blank=True, choices=[('HOME', 'home'), ('OFFICE', 'office'), ('OTHER', 'other')], max_length=100, null=True),
        ),
    ]
