# Generated by Django 5.2.1 on 2025-07-06 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0005_alter_shipping_address_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='address_type',
            field=models.CharField(blank=True, choices=[('home', 'Home'), ('office', 'Office'), ('other', 'Other')], max_length=100, null=True),
        ),
    ]
