# Generated by Django 5.2.1 on 2025-07-06 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_city_name_bn_country_name_bn_state_name_bn_and_more'),
        ('shipping', '0006_alter_shipping_address_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='union',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping', to='core.union'),
        ),
    ]
