# Generated by Django 5.2.1 on 2025-07-09 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0007_shipping_union'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
