# Generated by Django 5.2.1 on 2025-07-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0008_shipping_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='courier_service_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shipping',
            name='courier_service_tracking_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
